version: '3.8'

services:
  python-app:
    build:
      context: .
      dockerfile: app/Dockerfile.python
    container_name: python_app_0917
    volumes:
      - ./app/back-end:/app/back-end
    depends_on:
      - mysql

  node-app:
    build:
      context: .
      dockerfile: app/Dockerfile.node
    container_name: node_app_0917
    volumes:
      - ./app/front-end:/app/front-end
    depends_on:
      - mysql


  mysql:
    image: mysql:8.0
    container_name: mysql_db_0917
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3308:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
